version: "3.9"
services:
  flaskapp:
    build: .
    container_name: flask-keycloak-demo
    ports:
      - "5000:5000"
    environment:
      KEYCLOAK_URL: "http://localhost:8082"   # your running Keycloak
      REALM: "demo-realm"                     # you will create this
      CLIENT_ID: "flask-app"                  # you will create this
    restart: always
