version: "3.9"

services:
  flaskapp:
    build: .
    container_name: flask-keycloak-demo
    ports:
      - "5000:5000"
    environment:
      KEYCLOAK_URL: "http://keycloak:8080"
      REALM: "demo-realm"
      CLIENT_ID: "flask-app"
    depends_on:
      - keycloak
    restart: always

  keycloak:
    image: quay.io/keycloak/keycloak:26.4.6
    command: start-dev
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8082:8080"
    restart: always
