version: "3.9"

services:
  flaskapp:
    build: .
    container_name: flask-keycloak-demo
    ports:
      - "5000:5000"
    environment:
      KEYCLOAK_URL: "http://192.168.0.100:8080"
      REALM: "demo-realm"
      CLIENT_ID: "flask-app"
    restart: always
